// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0FI3wEa5ZMBWrI3lqBEVveJsQeHGIbM',
    appId: '1:289982922640:web:e2d82a3543fc2580bcfd15',
    messagingSenderId: '289982922640',
    projectId: 'fireapp-d33ab',
    authDomain: 'fireapp-d33ab.firebaseapp.com',
    storageBucket: 'fireapp-d33ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD00tWsiAtfzZdtqANUoJc4kGbMk_kXf08',
    appId: '1:289982922640:android:53775e2040cdacfabcfd15',
    messagingSenderId: '289982922640',
    projectId: 'fireapp-d33ab',
    storageBucket: 'fireapp-d33ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARowW_W1gcHfp-rho4RqDDog_kOvyxZns',
    appId: '1:289982922640:ios:b7847be942673472bcfd15',
    messagingSenderId: '289982922640',
    projectId: 'fireapp-d33ab',
    storageBucket: 'fireapp-d33ab.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARowW_W1gcHfp-rho4RqDDog_kOvyxZns',
    appId: '1:289982922640:ios:aa03c99dcf4667bebcfd15',
    messagingSenderId: '289982922640',
    projectId: 'fireapp-d33ab',
    storageBucket: 'fireapp-d33ab.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
